from collections import namedtuple
a = namedtuple('Person', ['name', 'male', 'age'])
print(a)
a = namedtuple('Person', ('name', 'male', 'age'))
print(a)
a = namedtuple('Person', {'name', 'male', 'age'})
print(a)
a = namedtuple('Person', {'name': 1, 'male': 2, 'age': 3})
print(a)
a = namedtuple('Person', 'name male age')
print(a)
a = namedtuple('Person', 'name,male,age')
print(a)
a = namedtuple('Person', map(str.strip, ['name ', ' male ', 'age']))
print(a)