# def password_gen():
#     for i in range(10):
#         for j in range(10):
#             for k in range(10):
#                 yield str(i) + str(j) + str(k)

from itertools import product

def password_gen():
    lst = [str(i) for i in range(10)]
    for comb in product(lst, repeat=3):
        yield ''.join(comb)

passwords = password_gen()
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))
print(next(passwords))